name: 'FTP Deploy Plugin'
description: 'Deploy plugin files via FTPS, excluding dev and CI artefacts.'

inputs:
  username:
    description: 'FTP username'
    required: true
  password:
    description: 'FTP password'
    required: true

runs:
  using: composite
  steps:
    - uses: SamKirkland/FTP-Deploy-Action@v4.4.0
      with:
        server: erfindergeist.org
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        local-dir: ./
        protocol: ftps
        state-name: .ftp-deploy-calendar-wp-plugin-state.json
        exclude: |
          **/.git*
          **/.git*/**
          **/.github*
          **/test*
          **/test*/**
          **/docs*
          **/docs*/**
          **/phpcs.xml
          **/phpstan.neon
          **/phpstan-bootstrap.php
          **/psalm.xml
          **/.phpmd.xml
          **/composer.json
          **/Dockerfile
          **/compose.yml
