### 
GET https://spielwiese.erfindergeist.org/wp-json/erfindergeist/v2/nextevent

### events with ical
GET https://spielwiese.erfindergeist.org/wp-json/erfindergeist/v2/events

### ICS use Browser
https://spielwiese.erfindergeist.org/wp-json/erfindergeist/v2/ics
