### 
GET https://spielwiese.erfindergeist.org/wp-json/erfindergeist/v1/nextevent

### events with ical
GET https://spielwiese.erfindergeist.org/wp-json/erfindergeist/v1/events

### get feature
GET https://spielwiese.erfindergeist.org/wp-json/erfindergeist/v1/feature
