### 
GET https://spielwiese.erfindergeist.org/wp-json/erfindergeist/v2/nextevent

### events with ical
GET https://spielwiese.erfindergeist.org/wp-json/erfindergeist/v1/events

https://spielwiese.erfindergeist.org/wp-json/erfindergeist/v1/ics

