alias: tomorrow_reminder_discord
description: looks each day at 10am if there is an event tomorrow and sends a reminder to discord
triggers:
  - trigger: time
    at: "10:00:00"
conditions: []
actions:
  - action: rest_command.egj_tomorrow
    response_variable: tomorrow_response
    data: {}
  - if:
      - condition: template
        value_template: "{{ tomorrow_response['status'] == 200 }}"
    then:
      - action: notify.egj_homeassistant
        data:
          message: ""
          target: "913007797237604402"
          data:
            embed:
              title: >-
                Erinnerung für morgen:
                {{tomorrow_response['content']['summary']}}
              url: https://erfindergeist.org/veranstaltungen/
              color: 199363
              fields:
                - name: Beschreibung
                  value: "{{tomorrow_response['content']['description']}}"
                  inline: false
                - name: Ort
                  value: "{{tomorrow_response['content']['location']}}"
                  inline: false
                - name: Datum Uhrzeit
                  value: "{{tomorrow_response['content']['starttime']}}"
                  inline: false
mode: single