name: 🚀 Deploy PROD Stage calendar-wp-plugin

on:
  workflow_run:
    workflows: ['🧪 CI calendar-wp-plugin']
    types: [completed]
    branches: [main]

jobs:
  web-deploy:
    name: 🎉 Deploy at https://erfindergeist.org/
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v6

      - name: 🐘 PHP & Composer einrichten
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
          coverage: none

      - name: 📦 Produktions-Abhängigkeiten installieren
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: 📂 Sync files
        uses: ./.github/actions/ftp-deploy
        with:
          username: ${{ secrets.FTP_USERNAME_PROD }}
          password: ${{ secrets.FTP_PASSWORD_PROD }}
